import fs from 'fs';
import path from 'path';
import { Product } from '../types/product';

// We load the preprocessed JSON file generated by scripts/preprocess.ts
// This saves memory and avoids parsing the 51MB CSV on cold starts.
const JSON_PATH = path.join(process.cwd(), 'data', 'products.json');

export function loadProducts(): Product[] {
  try {
    if (!fs.existsSync(JSON_PATH)) {
      console.error(`Products JSON not found at ${JSON_PATH}. Run the preprocessor script.`);
      return [];
    }
    const fileContent = fs.readFileSync(JSON_PATH, 'utf8');
    const products: Product[] = JSON.parse(fileContent);
    return products;
  } catch (error) {
    console.error('Failed to load products JSON:', error);
    return [];
  }
}
